# Generated by Django 4.2.2 on 2023-07-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=180)),
                ('description', models.CharField(blank=True, default='', max_length=180)),
                ('author', models.CharField(blank=True, default='', max_length=180)),
                ('link', models.CharField(blank=True, default='', max_length=180)),
                ('subject', models.CharField(blank=True, default='', max_length=180)),
            ],
        ),
    ]
