# Generated by Django 4.2.2 on 2023-08-03 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseLister_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=180)),
                ('description', models.CharField(blank=True, default='', max_length=180)),
                ('author', models.CharField(blank=True, default='', max_length=180)),
                ('subject_matter', models.CharField(blank=True, default='', max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='LessonDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=180)),
                ('chapter_number', models.CharField(blank=True, default='', max_length=180)),
                ('description', models.CharField(blank=True, default='', max_length=180)),
                ('course_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='courseLister_api.coursesummary')),
            ],
        ),
        migrations.CreateModel(
            name='LessonLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_start', models.CharField(blank=True, default='', max_length=180)),
                ('url_link', models.CharField(blank=True, default='', max_length=180)),
            ],
        ),
        migrations.DeleteModel(
            name='CourseList',
        ),
    ]
